### ISSUE TITLE
Missing dict.txt file

### ISSUE THREAD

**Issue by souzajc** [patrickfriedman/Classification-of-Subjective-and-Objective-Texts-Using-RNN#8]
Hello.

I'm trying to run you code but it's missing dict.txt, could you please share the file or let me know its content and format?

Thank you very much.
Regards.
Jeff.

**Comment by patrickfriedman** [comment]
Thanks for the heads up, I uploaded the dict.txt file that we used.
Can I ask what you are using this for?

**Comment by souzajc** [comment]
HI Patrick,

Thank you very much for the upload.

I'm trying to explore cognitive solutions for the company I work for.
This company has developed a web studying platform - its launch was anticipated due Covid's pandemic.
I'm checking your code to understand how to identify subjective/objective comments in this platform.
I want to explore objective comments in my study for starting.

Regards.

Jeff
________________________________
